//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIOS
    {
        public int ID_USUARIO { get; set; }
        public int ID_JERARQUIA { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public string FECHA_NACIMIENTO { get; set; }
        public string RFC { get; set; }
        public string MATRICULA { get; set; }
        public Nullable<int> JEFEID { get; set; }
        public Nullable<bool> FACTURA { get; set; }
        public string AREA { get; set; }
        public string ESTRATEGIA { get; set; }
        public string CTA_COPPEL { get; set; }
        public string CVE_INTERBANCARIA { get; set; }
        public string CTA_SALDAZO { get; set; }
        public string CTA_BANORTE { get; set; }
        public string ESTRATEGIA_GERENTE_PROMOTOR { get; set; }
        public string USUARIO_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public string USUARIO_ACTUALIZACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
        public string DIRECCION_OFICINA { get; set; }
        public string TELEFONO_OFICINA { get; set; }
        public string NOMBRE_RENTERO { get; set; }
        public string TELEFONO_RENTERO { get; set; }
    }
}
