//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPRD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JudaPRDEntities : DbContext
    {
        public JudaPRDEntities()
            : base("name=JudaPRDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_FOLIOS> TBL_FOLIOS { get; set; }
        public virtual DbSet<TBL_PCT_COMISION> TBL_PCT_COMISION { get; set; }
        public virtual DbSet<TBL_CLAVE_PROMOTOR> TBL_CLAVE_PROMOTOR { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public virtual DbSet<TBL_JERARQUIA> TBL_JERARQUIA { get; set; }
        public virtual DbSet<TBL_ARCHIVO_USUARIO> TBL_ARCHIVO_USUARIO { get; set; }
    }
}
