//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public int ID_JERARQUIA { get; set; }
        public Nullable<int> ID_JEFE { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string RFC { get; set; }
        public string MATRICULA { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
    
        public virtual TBL_JERARQUIA TBL_JERARQUIA { get; set; }
    }
}
