//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PCT_COMISION
    {
        public int ID_PCT_COMISION { get; set; }
        public Nullable<int> ID_JERARQUIA { get; set; }
        public Nullable<decimal> PCT { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
    
        public virtual TBL_JERARQUIA TBL_JERARQUIA { get; set; }
    }
}
