//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_USUARIO()
        {
            this.TBL_CLAVE_PROMOTOR = new HashSet<TBL_CLAVE_PROMOTOR>();
            this.TBL_ARCHIVO_USUARIO = new HashSet<TBL_ARCHIVO_USUARIO>();
        }
    
        public int ID_USUARIO { get; set; }
        public int ID_JERARQUIA { get; set; }
        public Nullable<int> ID_JEFE { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public string APELLIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string NOMBRE { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string CURP { get; set; }
        public string RFC { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public byte[] FOTO { get; set; }
        public Nullable<bool> CHECK_RH { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_ACTUALIZACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_CLAVE_PROMOTOR> TBL_CLAVE_PROMOTOR { get; set; }
        public virtual TBL_JERARQUIA TBL_JERARQUIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ARCHIVO_USUARIO> TBL_ARCHIVO_USUARIO { get; set; }
    }
}
