//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloPRD
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARCHIVO_USUARIO
    {
        public int ID_ARCHIVO_USUARIO { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public byte[] ARCHIVO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
    
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
